#!/usr/bin/env bash
# Records scripts/run_all_demos.py with VHS (GIF + WebM, both via VHS's own
# defaults), uploads both via the gh-image extension, and rewrites the demo
# block in README.md (between the demo:start/demo:end markers) to embed the
# uploaded WebM as an inline autoplaying video, with the GIF as a static
# alternate.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TAPE_FILE="${SCRIPT_DIR}/demo.tape"
README_FILE="${REPO_ROOT}/README.md"
ASSETS_DIR="${REPO_ROOT}/assets"
GIF_FILE="${ASSETS_DIR}/demo.gif"
WEBM_FILE="${ASSETS_DIR}/demo.webm"

need() {
    local bin="$1" brew_pkg="$2"
    if ! command -v "${bin}" >/dev/null 2>&1; then
        echo "error: ${bin} is not installed." >&2
        echo "Install it with: brew install ${brew_pkg}" >&2
        exit 1
    fi
}

need vhs vhs
need gh gh

if ! gh extension list | grep -q 'drogers0/gh-image'; then
    echo "Installing the gh-image extension..."
    gh extension install drogers0/gh-image
fi

cd "${REPO_ROOT}"
REPO_SLUG="$(gh repo view --json nameWithOwner -q .nameWithOwner)"

mkdir -p "${ASSETS_DIR}"

echo "Timing scripts/run_all_demos.py to size the recording..."
start=$(date +%s)
uv run python scripts/run_all_demos.py >/dev/null 2>&1
end=$(date +%s)
elapsed=$(( end - start ))
sleep_seconds=$(( elapsed + 3 ))
echo "Demo run took ${elapsed}s; recording with a ${sleep_seconds}s sleep."

cat >"${TAPE_FILE}" <<EOF
# Records scripts/run_all_demos.py for scripts/build_demo_gif.sh.
# Generated by scripts/build_demo_gif.sh - run that instead of editing by hand.

Output "${GIF_FILE}"
Output "${WEBM_FILE}"

Require uv

Set Shell "bash"
Set FontSize 22
Set Width 1300
Set Height 680
Set Padding 15
Set Theme "Dracula"

Hide
Type "clear"
Enter
Show

Type "uv run python scripts/run_all_demos.py"
Enter
Sleep ${sleep_seconds}s
EOF

vhs "${TAPE_FILE}"

echo "  demo.gif: $(du -h "${GIF_FILE}" | cut -f1)"
echo "  demo.webm: $(du -h "${WEBM_FILE}" | cut -f1)"

echo "Uploading to ${REPO_SLUG}..."
refs="$(gh image "${GIF_FILE}" "${WEBM_FILE}" --repo "${REPO_SLUG}")"
echo "${refs}"

gif_ref="$(printf '%s\n' "${refs}" | sed -n '1p')"
webm_ref="$(printf '%s\n' "${refs}" | sed -n '2p')"
gif_url="$(printf '%s' "${gif_ref}" | grep -oE '\(https://[^)]+\)' | tr -d '()')"

demo_md="${webm_ref}

<sub>Prefer a static image? [GIF](${gif_url})</sub>"

echo "Updating README.md demo block..."
DEMO_MD="${demo_md}" perl -0777 -pe '
    s/(<!-- demo:start -->\n).*?(\n<!-- demo:end -->)/$1 . $ENV{DEMO_MD} . $2/se
' "${README_FILE}" > "${README_FILE}.tmp"
mv "${README_FILE}.tmp" "${README_FILE}"

echo "Done. README.md updated with the new demo embed."
