#!/usr/bin/env bash
# Regenerates scripts/demo.tape (sized to the current demo runtime) and
# records it into assets/demo.gif via VHS.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TAPE_FILE="${SCRIPT_DIR}/demo.tape"
GIF_FILE="${REPO_ROOT}/assets/demo.gif"

if ! command -v vhs >/dev/null 2>&1; then
    echo "error: vhs is not installed." >&2
    echo "Install it with: brew install vhs" >&2
    exit 1
fi

cd "${REPO_ROOT}"

echo "Timing scripts/run_all_demos.py to size the recording..."
start=$(date +%s)
uv run python scripts/run_all_demos.py >/dev/null 2>&1
end=$(date +%s)
elapsed=$(( end - start ))
sleep_seconds=$(( elapsed + 3 ))

echo "Demo run took ${elapsed}s; recording with a ${sleep_seconds}s sleep."

cat >"${TAPE_FILE}" <<EOF
# Records scripts/run_all_demos.py into assets/demo.gif.
# Generated by scripts/build_demo_gif.sh - run that instead of editing by hand.

Output assets/demo.gif

Require uv

Set Shell "bash"
Set FontSize 16
Set Width 1000
Set Height 680
Set Padding 15
Set Theme "Dracula"

Hide
Type "clear"
Enter
Show

Type "uv run python scripts/run_all_demos.py"
Enter
Sleep ${sleep_seconds}s
EOF

mkdir -p "${REPO_ROOT}/assets"
vhs "${TAPE_FILE}"

echo "Wrote ${GIF_FILE} ($(du -h "${GIF_FILE}" | cut -f1))"
